apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: bookinfo
  labels:
    app: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql:5.7
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 300Mi
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 3306
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 3306
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 2
            initialDelaySeconds: 20
          envFrom:
          - configMapRef:
              name: db
          env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_PASSWORD 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_ROOT_PASSWORD           
          volumeMounts:
            - mountPath: /var/lib/mysql 
              name: test-volume
  volumeClaimTemplates:
  - metadata:
      name: test-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
      storageClassName: "longhorn"   
---
apiVersion: v1
kind: ConfigMap
data:
  MYSQL_CONNECTION: mysql
  MYSQL_HOST: "db"
  MYSQL_DATABASE: "db"
  MYSQL_USER: "user"
  MYSQL_LOGGING: ""
  LOCALTIME: Europe/Moscow
  MYSQLD__collation-server: utf8_unicode_ci
  MYSQLD__character-set-server: utf8
  MYSQLD__innodb_flush_log_at_trx_commit: "2"
  MYSQLD__innodb_flush_method: O_DIRECT
  MYSQLD__transaction-isolation: READ-COMMITTED
  MYSQLD__default_authentication_plugin: mysql_native_password
  MYSQLD__sql_mode: ""
  MYSQLD__max_connections: "60"
metadata:
  name: db
  namespace: bookinfo
---
apiVersion: v1
metadata:
  name: db-secret
  namespace: bookinfo
kind: Secret
type: Opaque
data:
  MYSQL_PASSWORD: "cGFzcw=="
  MYSQL_ROOT_PASSWORD: "cGFzcw=="
  REDIS_PASS: "V0R5d3VxdXJ1V3lTbkI="
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: bookinfo
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: db
  type: ClusterIP  