---
apiVersion: v1
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
kind: Secret
type: Opaque
data:
  MYSQL_PASSWORD: "cGFzcw=="
  MYSQL_ROOT_PASSWORD: "cGFzcw=="
  REDIS_PASS: "V0R5d3VxdXJ1V3lTbkI="
  POSTGRES_PASSWORD: "cGFzcw=="