---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: tcp-redis
  selector:
    app: redis
  type: ClusterIP   