nodeselector: {}
namespace: bookinfo

images:
  app:
    image: registry.sovcombank.group/s-devops/docker.io/istio/examples-bookinfo-productpage-v1
    pullPolicy: IfNotPresent
    tag: "1.17.6"

deployments:
  app:
    name: app
    replicas: 1
    labels:
      app: productpage
      version: v1
    port: 9080
    resources:
        limits:
          cpu: 300m
          memory: 300Mi
        requests:
          cpu: 100m
          memory: 128Mi
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 9080
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
      initialDelaySeconds: 10
    livenessProbe:  
      failureThreshold: 3
      httpGet:
        path: /
        port: 9080
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
      initialDelaySeconds: 10        

variables:
  app:
    OTEL_TRACES_EXPORTER: "otlp"
    OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
    OTEL_SERVICE_NAME: "productpage" 
    OTEL_EXPORTER_OTLP_ENDPOINT: "coroot-opentelemetry-collector.coroot:4317"
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://coroot-opentelemetry-collector.coroot:4318/v1/traces"
    OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: "http/protobuf"
    OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
    NO_PROXY: "127.0.0.1,localhost,.sovcombank.group,minio,.sovcombank.ru,coroot-clickhouse,.coroot,coroot-opentelemetry-collector.coroot,.coroot.svc.cluster.local,ratings,details,reviews"
    MYSQL_HOST: "db"
    MYSQL_USER: "user"
    MYSQL_DATABASE: "db"
    HOST_REDIS: "redis"
    POSTGRES_DB: "db"
    POSTGRES_HOST: "postgres"
    POSTGRES_USER: "user"

secret:
  app: []

ingress:
  app: bookinfo-k8s-test.sovcombank.group

nodeSelector: {}

tolerations: []

affinity: {}

securityContext: {}

podSecurityContext: {}