---
apiVersion: v1
kind: ConfigMap
data:
  MYSQL_CONNECTION: mysql
  MYSQL_HOST: "db"
  MYSQL_DATABASE: "db"
  MYSQL_USER: "user"
  MYSQL_LOGGING: ""
  LOCALTIME: Europe/Moscow
  MYSQLD__collation-server: utf8_unicode_ci
  MYSQLD__character-set-server: utf8
  MYSQLD__innodb_flush_log_at_trx_commit: "2"
  MYSQLD__innodb_flush_method: O_DIRECT
  MYSQLD__transaction-isolation: READ-COMMITTED
  MYSQLD__default_authentication_plugin: mysql_native_password
  MYSQLD__sql_mode: ""
  MYSQLD__max_connections: "60"
metadata:
  name: db
  namespace: {{ .Values.namespace }}