---
apiVersion: v1
kind: ConfigMap
data:
  POSTGRES_DB: "db"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres" 
  POSTGRES_USER: "user"
  TZ: Europe/Moscow
  PGTZ: Europe/Moscow 
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}